ANSHIKA-26/WordWise

blog.html, category.html, index.html, start.html
changed redirection of logo to home page
Note : - please add level and Hacktoberfest tag for tracking my contribution
redirects to home page...
=> changed redirection of logo

style.css
**Made sure the header and footer match**
**This pull request includes the following changes:**
- Restyled the footer to improve visual aesthetics and user experience.
- Updated CSS styles to ensure consistency with the overall design of the website.
**Screen shot**
=> Fixted Footer background color and text for better visibility issue #3

blog.html, category.html, darkMode.js, index.html, start.html, style.css
@ANSHIKA-26 
https://github.com/user-attachments/assets/824c6640-496d-4bf2-8a23-78efb8470ba8
the darkmode is functioning well for all the pages.
=> darkMode toggle created!

.vscode/settings.json, darkMode.js, style.css
**Screenshot**
**Dark Mode**
**Light Mode**
---
**Dark Mode**
**Light Mode**
---
If you cant any changes then I will do it.
Issue no #97
=> Color fixed

index.html
=> Improve Hover Effect

index.html, style.css
- [Yes] I have added screenshots and videos to show the working of my code.
- [Yes ] I have ensured that the screen size is set to 100% while making the video.
- [Yes ] I have synced the latest fork with my local repository and resolved any conflicts.
- Here is the screenshot for your reference
https://github.com/user-attachments/assets/e806f7fe-a86b-49a4-8848-2aa155f1972d
=> I have changed the footer and also changed the color palette to make it look more aesthetic. Issue #48

index.html, style.css
- [ X] I have added screenshots and videos to show the working of my code.
=> #33 navbar issue solved

index.html
I connect links to there button 
https://github.com/user-attachments/assets/91093cae-b367-46b8-bbd7-309dccd7d5a8
=> Existing files links added to button

index.html
This PR change the load more post button.
##fixes issue #123
=> redesign load more post

index.html, style.css
Enhanced Footer :
Screenshot before editing:
Screenshot After editing: 
fixes #71
=> enhanced the footer and dark theme also

about.html, blog.html, category.html, contact.html, start.html
I have made the text in  About us section in side the footer visible
=> Made the footer text visible #126

index.html, style.css
=> Slider images

index.html, share.js, style.css
=> Social media share feature

category.html
=> navbar background added 

index.html, style.css
- Final changes: hide the scrollbar and fix navbar margin height  
kindly check this PR and do merge it as well 
Fixes #153 
I have added screenshots and videos to show the working of my code.
I have ensured that the screen size is set to 100% while capturing the screenshot.
I have synced the latest fork with my local repository and resolved any conflicts.
=> hide scrollbar and fix navbar

index.html, style.css
HTML Enhancements:
Added aria-label attributes for accessibility, allowing screen readers to understand the purpose of elements. Ensured that dropdown links are wrapped in a div with appropriate classes. CSS Enhancements:
Media Queries: Added responsiveness for screens smaller than 768px, stacking the navigation links vertically and adjusting padding/margins.
Hover Effects: Improved hover states with increased opacity for better visibility.
Padding and Margin: Adjusted padding and margins for better alignment and touch-friendly interactions.
Flexbox Alignment: Improved the layout with flexbox properties for better alignment and spacing.
=> Navbar arrangements

style.css
=> [FIX] Landing page overflow-X fixed

style.css
https://github.com/user-attachments/assets/f19b9371-75fb-46d1-a893-6cde8158adc6
=> Solved Issue where image does not overlaps text.

index.html, style.css
=> updated NavBar 

index.html
I updated the Twitter icon in the footer section
=> Update index.html for Twitter icon

index.html
After
- [ Done] I have added screenshots and videos to show before and after the working of my code.
- [ Done] I have ensured that the screen size is set to 100% while making the video.
- [Done ] I have synced the latest fork with my local repository and resolved any conflicts.
- [ Done] I understand that if any the above conditions are not met , my PR will not be MERGED .
=> enhanced symmetry and size of photos

contact_us.html, start.html
=> Added separate contact us form with responsive design : Issue no #54

index.html, style.css
- Fixes #154 
- Scroll bar removed
- Login and Sign up button hover effect added
=> [FIX] Nav bar issue fixed

index.html, style.css
Reverts ANSHIKA-26/WordWise#226
=> Revert "[FIX] Nav bar issue fixed"

about.html, share.js
Sharing feature added with reforked branch @hiteashgupta1 please check.
=> Sharing Feature Added 

about.html, blog.html, category.html, contact.html, darkMode.js, index.html, style.css
https://github.com/user-attachments/assets/c0b0c02c-e6f0-4249-a48a-e53ba6db5a92
=> dark mode and the Navbar feature working!

about.html, blog.html, category.html, contact.html, contact_us.css, contact_us.html, index.html, style.css
=> All the pages fixed

about.html, blog.html, category.html, contact.html, index.html, start.html
Email link added to every page
=> Email link

index.html, main.js, style.css
=> Login and signup buttons working

index.html, style.css
I have added a Newsletter which is associated with a subscribe button once a user enters his email address.
Furthermore I added the Authentication Copyright at the Footer section which would definitely ensure the authenticity of WordWise.
Please check out the snippets below for both the modifications
=> Newsletter added and Footer modified

index.html
=> SOLVED THE REDIRECTING ISSUE

backend/package-lock.json, backend/package.json, backend/server.js, contact_us.html
=>  Integrated Email Sending Backend : Issue no #287

index.html, style.css
Adding gaps in tags and social icons and change color and make structured
=> Adding gaps in tags and social icons and change color and make structured

index.html, style.css
=> In the footer section Feature Post section updated

about.html, blog.html, category.html, contact_us.css, contact_us.html, index.html, start.html
Issue: Navbar was not consistent in each page as well as start writing button was missing
Fixed: Made navbar consistent in all pages, added start writing button to all pages
Before:
After:
Apart from this issue, there are several issues in website:
1. No give feedback page
2. No favicon
3. No Back to top bottom
4. Not responsive 
5. No start writing page
I can fixed all these 5 issues if you assign these project to me to fix all bugs
Please add labels to this issue as well.
- [ YES] I have added screenshots and videos to show before and after the working of my code.
- [YES ] I have ensured that the screen size is set to 100% while making the video.
- [YES ] I have synced the latest fork with my local repository and resolved any conflicts.
- [YES ] I understand that if any the above …
=> made navbar consitent, start writing button visible in all pages

contact_us.html
=> display a popup message after submitting get in touch form and add message length validation

style.css
Hey, i just added a box shadow effect to each cards in your website, Take a look!!
Issue number: #319
https://github.com/user-attachments/assets/db9c11e4-9144-43f0-8446-0b8318a61a4a
This box shadow effect enhances the UI of your website, hope you like it.
and the red colour goes good with your website theme! 
Please label me under gssoc and hacktober fest with level. Thank You 🙏
=> Cards hover effect added |  #319

category.html, index.html
In the Categories page Footer section updated
#374
=> In the Categories page Footer section updated

index.html, style.css
=> Home page Slider Picture override width of page issue is solved

faq.js, index.html, style.css
**_Added rotating effect to '+' icons so when the question is expanded they rotate to become 'x'_**
_**Added borders and padding to make UI more appealing**_
_**preserved the feature that allows only one FAQ to be expanded at a time**_
_**when another FAQ is active the previously active FAQs automatically shrink Smoothly while also rotating the 'x' icon to its original '+' shape**_
**_BEFORE_**
_**AFTER**_
https://github.com/user-attachments/assets/ed306a76-1bcf-44d2-9d4d-fc2ee0f36b18
_**Issue No: #364 **_
=> [Enhancement Done]Enhanced FAQ UI #364

index.html, style.css
load more posts button before :
after : 
this fixes issue #346 .
=> Improved Load More Posts Button UI

index.html
before improving date and comment icons of each post card : 
after improving :
this fixes issue #389 .
=> improved date and icons

backend/newsLetter.js, backend/server.js, index.html, style.css
1. I have added Email Validation by  regex addition to ensure that the user inputs a valid email address before subscribing.
2. Additon of  toast-style popup notification to provide immediate feedback to the user. It shows a success message when the subscription is successful and an error message in case of failure or invalid email input (Initially Error as the Provider Email and Password should enter by the Admin).
Issue #289 Completed
https://github.com/user-attachments/assets/d42fa79e-718d-4596-8a13-09767b76c0db
=> Addition of Email Validation, Toast Alert PopUp, Newsletter Endpoint and Newsletter Service | Issue #289

index.html, style.css
fixes #362 
https://github.com/user-attachments/assets/4a76b0cf-05a6-42d5-a880-08b2981b24c9
=> updated toggle button ui

style.css
<h2>Issue Number:- #378 </h2>
Successfully added size transform feature and color change effect on hover of social icons.
<h3>Before:</h3>
https://github.com/user-attachments/assets/24baca82-8d96-42b9-9b7a-8ec341f8db68
<h3>After</h3>
https://github.com/user-attachments/assets/5fbc3f97-a9d7-429f-bead-3a3f001c075c
=> added hover effect to social icons

index.html
Solves issue #376 
Here is the image of the proposed work:
**Before**
**After**
@ANSHIKA-26 Please do let me know if the work needs any changes or update.
=> add website views widget #376

blog.html, contact_us.html, index.html, start.html, start_writing.css, start_writing.html, start_writing.js
https://github.com/user-attachments/assets/ee444007-83ff-4a24-b459-e390f31bf07d
=> Fixes #410

style.css
fixes #223 
Updated scrollbar styling for light and dark modes with hover effects and rounded edges
**Before -**
https://github.com/user-attachments/assets/89016569-c2ef-48c1-b5a6-9d84fe4ac338
**After -**
https://github.com/user-attachments/assets/ba9d4036-46bc-439a-816d-1b0265d77c61
=> Updated scrollbar styling for light and dark modes 

blog.html, style.css
=> Enhanced Submit Button fixes issue number #303

index.html, style.css
**Applied styling on Preloader and changed preloader loading behaviour 
Applied styling on loading screen**
- change the style Preloader
- change the animation style Preloader
fixes #392
=> Improve Preloader

backend/signUp/signup.js, index.html, styles.css
This pull request enhances the signup functionality by adding validation for email format and password strength, ensuring users create secure accounts. It also introduces a password visibility toggle feature for improved user experience.
=> issue #414 Enhanced Signup Functionality with Validation and Password Visibility Toggle

blog.html
✅ I have added screenshots and videos to show before and after the working of my code.
✅ I have ensured that the screen size is set to 100% while making the video.
https://github.com/user-attachments/assets/76d6605a-1d94-4b5d-a0b5-1c6a4e3afdc1
https://github.com/user-attachments/assets/0d8f9703-2ea5-40ea-b6f7-cedfac6319a2
✅ I have synced the latest fork with my local repository and resolved any conflicts.
✅ I have mentioned the issue number which I created before making this PR. (format to mention issue number is: fixes #(issue number))
✅ I understand that if any of the above conditions are not met, my PR will not be MERGED.
=> Duplicate Button issue solved (Issue #489)

Scroll_and_progressbar.css, about.html, blog.html, category.css, category.html, contact_us.html, index.html, progress_bar.js, start.html, start_writing.html, style.css
#397 
Hey @ANSHIKA-26 
I wanted to share a quick update on my progress. I've successfully added both the scroll bar and the progress bar to the project. The UI has become more interactive with these elements in place.
If you have any feedback or suggestions for further improvements, I’d love to hear them!
Thank you.
Best regards,
Before: with a basic scroll bar
After: adding scroll bar and progress bar
https://github.com/user-attachments/assets/cc11b5b2-c3a7-436a-98a3-37616a484945
=> scroll bar and progress bar added

index.html
#511 Done !!
https://github.com/user-attachments/assets/b92441e8-8063-4783-bcaa-a65f08f24eea
=> Fixed the Navbar Successfully !!

index.html, style.css
This PR addresses the issue #514 by enhancing the user experience  updating footer UI.
=> fix footer ui improvemnt

backend/server.js, contact_us.html, contact_us.js
hey @ANSHIKA-26  i connected your contact form with the backend now anyone can send message to you from website 
demo:
modal after email is sent:
**please don not forget to add gssoc-ext and level2 label before merge**
=> Added Email functionality to the contact form issue #506

index.html, script.js, style.css
This implementation centers a form and button using Flexbox and incorporates button effects along with user feedback upon submission:
1.Flexbox:
The form is set to display: flex; with flex-direction: column;, align-items: center;, and justify-content: center; for vertical and horizontal centering.
2.Button Centering:
The button is placed inside a div that uses display: flex; and justify-content: center; to center it.
3.Button Effects:
Added hover and active effects to the button:
Hover: Changes background color and lifts the button slightly when hovered over.
Active: Resets the lift effect and shrinks the button slightly when clicked.
4.Form Submission Handling:
Upon form submission, the default action is prevented using e.preventDefault();.
A success message is displayed after hiding the …
=> Centering a Form and Button in the Middle of the Screen Using Flexbox

index.html, script.js
Added check for '@' in the email address submitted by used.
https://github.com/user-attachments/assets/a9811c47-cb82-4ae5-8f51-bdfdb1646191
https://github.com/user-attachments/assets/fe04d31e-e488-4c99-8597-44e1bc2b781d
=> Newsletter Updation

index.html, style.css
**i hope you understand my work and provide me a level in for gssoc extd 2024**
=> added a simple and good pre loader

backend/Database.js, backend/modal/BlogModal.js, backend/package-lock.json, backend/package.json, backend/server.js, start_writing.html, start_writing.js
i created an Api which let the user to post the blogs along with the image 
database storage of data 
frontend
please add level3  and gssoc-ext before merge
=> Api for blog post and Mongodb connection issue #546

about.html, blog.html, category.css, category.html, contact_us.html, index.html, start_writing.html, style.css
This PR includes significant enhancements to the project, focusing on making the navigation bar and the cards in index.html and about.html layout fully responsive among other pages. The following changes were made to improve usability and aesthetics across various device sizes.
- fixes #257 
- **Responsive Navigation Bar**
- Added a toggle button for small screens.
- Implemented JavaScript for toggling menu visibility.
- **Category Layout Adjustments**
- Ensured one column of posts on small screens.
- Made category boxes responsive and stacked vertically on mobile.
- **Code Cleanup and Optimization**
- Removed redundant CSS and streamlined navigation code.
- Consolidated similar styles for clarity.
- **CSS Enhancements**
- Added media queries for responsiveness.
- Improved padding, …
=> Fixing responsiveness issues. 

contact_us.html, login.html, signup.html
The "Contact Us" page had outdated UI with a lack of visual appeal and responsiveness. It required modern styling to enhance user experience and make it more engaging.
**Modern and Responsive UI:**
- Enhanced the design with inline CSS to ensure responsiveness across devices (desktop, tablet, and mobile).
- Improved overall visual appeal using vibrant colors and a cleaner layout for better readability and interaction.
**Improved Form Styling:**
- Applied stylish input fields with appropriate padding, color contrast, and spacing.
- The button design was modernized with a hover effect and prominent positioning to improve user engagement.
**Popup Confirmation for Message Submission:**
- Styled the "Message Sent" confirmation popup to provide a smooth user experience with clear messaging upon …
=> Updated UI of the Contact Us Page 

contact_us.html, login.html, signup.html
Initially, the password toggle (eye) button was not aligned correctly inside the password input box. It appeared above the password field, disrupting the layout and user experience. Moreover, while the "Show Password" toggle functionality was present in the sign-up page, it wasn't included in the login page, leading to an inconsistent user experience across both forms.
- We adjusted the CSS for the eye button inside the password field by using `position: absolute;` and setting it at the right location, along with appropriate padding adjustments inside the input box to avoid any overlap.
- This ensures that the eye button is now perfectly aligned within the input box, providing a sleek and professional look.
- The "Show Password" toggle button functionality was added to both the **Login** …
=> Add password toggle functionality to both login and signup pages

category.css, category.html
Solved: #620 
**Screenshots:**
Previous Design:
Updated Design:
The update design is more appealing as well as responsive for all devices.
Mobile:
Tablet (768px):
PC Screen:
=> Improved card layout and styling in category page

google_signin.js, index.html, style.css
Solved: #375 
Video:
https://github.com/user-attachments/assets/b6c762d4-46f5-4a55-9f65-c43e9a7fd2d5
=> Added Google Signin Frontend

category.css, category.html
solved: #636 
Screenshots : 
BEFORE:
NOW:
video link 
https://drive.google.com/file/d/1ghuRfwJk_vkY8NmDpZ-sIJtCyayp2bt4/view?usp=drive_link
=> Modified the category card section with hover effects

index.html
=> Fixes#655:Login/signup page not properly aligned when opened

style.css
=> Fixed issue no.655 Login/signup page not properly aligned

about.html, blog.html, category.html, contact.html, contact_us.html, index.html, start_writing.html
I have successfully fixed the bug in the footer section.
And as you requested I have also removed the text stating "Created by Anshika".
Also did some extra task: As Contact Us page didn't had footer so added it.
issue number is : fixes #649 
please give it a level
=> Fixing_footer

about.html, blog.html, category.html, contact_us.html, index.html, main.js, start.html, start_writing.html, style.css
fixes #501 
https://github.com/user-attachments/assets/afc503be-e2cf-4203-bd32-b46b487d1393
i have created a forgot password modal
=> Forgot password modal added

blog.html, style.css
- Removed the Hover effect from the Image 
**Before**
**After**
- Provided margin to the Image for the Paragraph 
- The Post section part was not properly aligned ,So Improvised it.
**Before**
**After**
=> Enhanced the blog page ,Resolved #679   

index.html
Fixed #653 
https://github.com/user-attachments/assets/526a1f57-0778-4d3f-85c7-dc161f9f9859
https://github.com/user-attachments/assets/8140493d-c443-4662-ab1b-13e635dfb5c6
=> Bug fixed scroll to top button delay : Issue no #653

category.html
The twitter icon is added and the issue is also fixed.
After:
=> Fixes issue:#656:Icons in the Categories Page Bottom are not properly spaced and Twitter icon added

about.html, blog.html, category.html, contact_us.css, contact_us.html, index.html, profiledropdown.js, start_writing.html, style.css
=> Enhanced Navbar Design (Fixes #580)

index.html, style.css
ISSUE : #703 
✅ I have added screenshots and videos to show before and after the working of my code.
✅  I have ensured that the screen size is set to 100% while making the video.
✅ I have synced the latest fork with my local repository and resolved any conflicts.
✅  I have mentioned the issue number which I created before making this PR 
✅ I understand that if any the above conditions are not met , my PR will not be MERGED .
✅ I have added a like button in the blog cards. People who like the blog would hit the like button. 
Before : 
After : 
Uploading heart.mp4…
=>  NEW FEATURE : Like Button Added on the blog cards 

backend/signUp/signup.js, index.html, main.js
closes #595 
---
- Before
- After
=> Fix Chrome errors on home page

style.css
ISSUE : #744 
✅ I have added screenshots and videos to show before and after the working of my code.
✅ I have ensured that the screen size is set to 100% while making the video.
✅ I have synced the latest fork with my local repository and resolved any conflicts.
✅ I have mentioned the issue number which I created before making this PR
✅ I understand that if any the above conditions are not met , my PR will not be MERGED .
✅ I have added a like button in the blog cards. People who like the blog would hit the like button.
Before : 
after :
=> Submit Button Fixed

style.css
Hello PR,
Fixed issue number -  #733
PA @ANSHIKA-26
=> Fixed Header color for Light mode issue ! #733

style.css
Fixed issue #739
BEFORE-->
AFTER-->
=> Enhanced the Login and Signup titles visibility in dark mode

about.html, blog.html, category.html, contact_us.html, index.html, start_writing.html, style.css
**Before:**
https://github.com/user-attachments/assets/f604af8b-6970-4f1b-8d4d-276eae8b7f34
**After:**
https://github.com/user-attachments/assets/76b6396b-85bd-4499-97b6-b0ba546f07b6
- Changed the logo in the header to be a clickable link that redirects to the home page (`index.html`) across all pages.
- Previously, the logo was not functioning as a hyperlink, and users were unable to navigate back to the home page by clicking the logo.
- This update ensures that the logo is now hyperlinked and works consistently on all pages.
fixes #728 
please add the appropriate labels as in the issue.
=> Update logo to hyperlink to home page

about.html, blog.html, category.html, contact_us.html, index.html
=> Added password strength validation to signup page

category.css, category.html, fashion.html, food.html, health.html, index.html, life.html, style.css, tech.html, travel.html
Thanks @ANSHIKA-26 for assigning me this issue.
- Fixed #782 
- Added **_6 Pages_** for all 6 categories with header and footer and articles with images.
- Linked them to categories page.
- I have also improved design of hovering on categories page.
- ADDED support for dark mode also
Please merge this PR.
=> Added all 6 Pages for categories

blog.html, style.css
Hello PR,
Fixed issue number - #735 & #777
When you select Dark mode these icons color &  "Travel" text color blends with the background color,
Issue Fixed -
https://github.com/user-attachments/assets/a2cb6066-c6c9-4ddf-87a4-b194a0d6f3b1
these buttons in the navbar of the repository's UI is not aligned properly, these buttons should maintain the same alignment like website logo "WordWise" alignment.
Issue Fixed -
https://github.com/user-attachments/assets/83a61dc5-1923-4838-83fd-9364943490a7
Add "Leave Comments" icon boxes border, text color for dark mode & add shadow properly, & These changes make this website so beautiful.
Issue Fixed -
https://github.com/user-attachments/assets/169fa3e0-e06d-4552-a4c4-5e46389e09b5
@ANSHIKA-26 @hiteashgupta1
=> Fixed icons color, message box, text color &  buttons misalignment  in the navbar Issue ! #735 & #777

about.html
This PR removes the unnecessary "Load More Posts" button from the About Us page, which does not serve any functional purpose since there are no posts to load. This cleanup will improve the UI and enhance user experience.
Fixes #748
**Before**  
There is a "Load More Posts" button at the end of the About Us page.
**After**  
The "Load More Posts" button has been successfully removed from the About Us page, and the UI is cleaner.
https://github.com/user-attachments/assets/260c0cd5-a897-4437-a712-6e302bc30c43
Fixes #748
This change is straightforward and does not introduce any new features or break any existing functionality.
---
=> Removed Unnecessary Load More Posts button From About Us Page

Scroll_and_progressbar.css, index.html, style.css
=> fixed progress bar

index.html, style.css
Improvement in Blog Card on Main Page (Landing Page).
The card are also working fine in both Light and Dark mode.
Fixes/Improves: #660
https://github.com/user-attachments/assets/276bc44c-b8fb-4ed4-8486-82cb0db3befe
=> Improved Blog Card, Supported for Light and Dark Theme

style.css
=> fixed dark mode

contact_us.html, start_writing.css, style.css
Improved Hover effects on the buttons it was missing:
https://github.com/user-attachments/assets/4fb64410-0a51-48bf-9187-ff1c874d6cba
=> Resolved issue: #842

index.html, script.js, style.css
As i was working on the ui of the blogs , i finally made the button to work using javascript functions.
Here's the before clip of the index page:
[recording.webm](https://github.com/user-attachments/assets/392d38a6-6687-47da-8981-54319066ae18)
Now the after clip - 
[recording (1).webm](https://github.com/user-attachments/assets/b70311e3-1904-4fe6-84cc-5cb00a6e6991)
Although further improvements can be done which i am facing issues in such as animations of the cards etc.
fixes #866
=> Implemented the load posts functionality

backend/.env.example, backend/Database.js, backend/config/nodemailer.js, backend/controllers/NewsLetterController.js, backend/modal/NewsLetterModel.js, backend/package-lock.json, backend/package.json, backend/server.js, index.html, main.js
Newsletter storing in database and a email is being sent to user
https://github.com/user-attachments/assets/fbaa27c9-5430-4002-aee7-7f4b84cd16dd
Issue no - #673
=> Newsletter storing in database and a email is being sent to user

backend/config/nodemailer.js, backend/controllers/ContactController.js, backend/modal/ContactModel.js, backend/server.js, contact_us.html, contact_us.js, index.html
feedback backend integrated with thank you mail support
https://github.com/user-attachments/assets/9166b965-ee90-4984-8011-aca5ac75d33e
#672
=> feedback backend integrated with thank you mail support

index.html
Solved :
Issue no #836 
When we reload or start the website, a cool text animated preloader appears.
https://github.com/user-attachments/assets/00f14e85-9c70-4fea-a116-9d3b2fecf815
=> Added Animated Preloader : Issue no #836

start_writing.html
=> Improve alignment of start-voice button

blog.html, category.html, start_writing.html
#574 
added it in - category, blog and writing page, home page faq has a different section and contact review doesn't require it
=> added faq popup modal in all pages

blog.html, main.js, start_writing.html
scroll to top button added on leading blog and start writing
issue no - #833 
https://github.com/user-attachments/assets/196d167a-fec6-4187-979a-89da5cb0a772
=> scroll to top button added on leading blog and start writing

backend/.env.example, backend/server.js, contact_us.css, contact_us.html, contact_us.js
contact us issue solved : Contact us backend frontend working correctly. #837 done
#To create a passkey on the phone or computer you’re on:
1. Go to https://myaccount.google.com/signinoptions/passkeys.
2. Tap Create a passkey and then Continue.(You'll be required to unlock your device.)
3. A 16 character passkey is generated which you can use.
- [ 1] I have added screenshots and videos to show before and after the working of my code.
- [1 ] I have ensured that the screen size is set to 100% while making the video.
- [1 ] I have synced the latest fork with my local repository and resolved any conflicts.
- [1 ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [ 1] I understand that if any the above …
=> contact us issue solved : Contact us backend frontend working correctly #837 done

about.html, blog.html, category.html, contact.html, contact_us.html, health.html, index.html, life.html, privacy.html, start.html, start_writing.html, tech.html, travel.html
#662 
Added Privacy Policy Page link in the footer and made a Privacy policy page
This link is present in footer of every page
=> privacy policy page added fixes issue #662

start_writing.html
fixes: #626 
Description:
1. The existing FAQ modal functionality is preserved.
2.  The collaborative writing feature is implemented, including:
- Adding and displaying collaborators
- Simulating real-time collaboration
- Updating the PostBlog function to include collaborative content
3. The PostBlog function is updated to:
- Combine collaborative content with additional content
- Log all blog post details, including collaborators
- Reset the form and collaborative writing section after submission
4. A placeholder for voice input functionality is added (assuming it's implemented in start_writing.js).
5. All functionality is wrapped in a DOMContentLoaded event listener to ensure the DOM is fully loaded before executing the script.
=> Collaborative writing

about.html, blog.html, category.html, contact_us.html, google_signin.js, index.html, main.js, start.html, start_writing.html, style.css
=> Navbar for mobile view

backend/model/User.js, backend/package.json, backend/server.js, backend/signUp/signup.js, login.html
Fixes #961 Adding core logic of login and signup using database.
Require model in Signup.js
Checking existing user in DB if it is not found then call to createUser function:
Create User password not stored directly because it is not secure to store same password i.e. I used bcrypt hashing for storing the password in the hashed form:
Login function logic bcrypt.compare() it check the current password and hashed form of password:
Database Schema for userModel:)
=> Feat: Implement login and signup backend core logic using DB

index.html, style.css
=> Update Scrollup button #919

index.html, style.css
=> Update Footer design #920

give_feedback.css, give_feedback.html, give_feedback.js, index.html
Pull Request Checklist
fixes #927
=> Feat: RevampFeedForm

blog-comment.js, index.html
Fixes #1010 Remove the overflow from home page and now it will not overflow in x-direction.
Screenshot:
https://github.com/user-attachments/assets/cfb4192a-17f9-4e88-b854-c802c0d69ba6
@ANSHIKA-26 Please review my PR and merge with **levels**.
=> Bug: Overflow-x direction

blog-comment.js
Fixes #1011 Edit the text color of faqs page now it visible properly! 
Screenshots:
@ANSHIKA-26 Please review my PR and assign the **level** and merge it:)
=> BUG: Edit faqs page text color

style.css
#Issue number: #979 Enhanced the visuals of the navbar "WordWise" Effects
Please assign this to me under level-1 of Gssoc'24 and Hacktoberfest.
=> Enhancing the visuals of the navbar "WordWise" Effects

start.html
#1027 yes, I have Improved it 
After:
=> Enhanced in footer

blog.html, style.css
@ANSHIKA-26 
successfully changed the layout.
fixes #1016 
before
after
=> styling done

darkMode.js
fixes issue no. - #658 
explanation  = i  have made a simple system in js which detects the systems color mode and auto sets the theme of the site based on it as said in issue #658 
explanation of the video = the theme was light on the local storage  I  cleared it and now when i refreshed with no preset theme the system auto changed it to dark which was my  laptop's theme already 
https://github.com/user-attachments/assets/b239ac77-ac7a-45ce-8323-0f786715c34c
=> fixed #658

README.md
This pull request addresses the issue of broken links in the `README.md` file. All non-functional links have been identified and corrected to ensure smooth navigation and better user experience.
- Fixed broken links in the `README.md` file.  
- Verified all updated links to ensure they point to the correct resources.  
- Improved accessibility to documentation and external references.  
- Enhanced user experience by eliminating dead links.  
- Manually checked each link to confirm they are working correctly.
Fixes #1025
@ANSHIKA-26
Pls give me level2,gssoc-extd,hacktoberfest,etc.
=> Solved Links not working in the readme.md file

style.css
- Identified duplicate position property assignments (relative and sticky) within the `style.css` file, leading to potential conflicts in styling for the navbar.
- Noted that the `layout-container` class was used inconsistently across multiple HTML files, affecting the navbar's visibility and behavior during scrolling.
- **Name:** Divanshi Goyal
- **GitHub ID:** divanshiii09
- **Email ID:** divanshigoyal051209@gmail.com
- **Closes:** #996
- **Duplicate Position Assignment:**
- **Files Affected:** `about.html`, `blog.html`, `category.html`, `contact.html`, `index.html`, `privacy.html`, `start_writing.html`
- Reviewed the usage of the `layout-container` class for the navbar, which had both relative and sticky positions defined.
- Chose the position *sticky* over *relative* in all mentioned …
=> Bugfix: Correct Navbar Positioning Issues in style.css (#996)

backend/package-lock.json, backend/package.json, backend/server.js
what i did:
created login route
i have added a express rate limiter to the login api 
it will:
prevent bot attacks 
reduce the load on thr api 
make the application more secure
image:
backend working:
please add gssoc-ext and level3 before merge @ANSHIKA-26
=> added express rate limiter issue #973

backend/Database.js, backend/config/nodemailer.js, backend/model/User.js, backend/server.js
Closes #853 
Screenshots:
workflow: 
1. user enters his email id
2. if email is valid a new otp is generated and sent to user's mail id
3. user enter otp
4. if otp is valid, user get redirect to reset password screen
5. user enters his new password
=> Forgot password

category.html, style.css
Fixes #1041 
After:
https://github.com/user-attachments/assets/3681c06e-8f2c-44e7-bc48-da012c489f8d
=> Added new hover effect to category section's buttons

backend/.env.example, backend/server.js, signup.html
Closes #1047 
Screenshots:
signup api:
login api:
mongodb:
=> added login and signup backend functionality

category.html
#370 
improve code of category page - Ensure that the dark/light mode persists after page reloads by using localStorage or cookies in JavaScript.
=> Update category.html theme switch improvement

blog.html
Hello, PR
Issue Fixed - #851 #1063
=> Fixed issue !

index.html
This pull request fixes the alignment issue of the heart (like) icon in the **Gaming Chronicles** card. The heart icon was previously not aligned with the calendar and chat icons. This slight adjustment improves the visual consistency across all cards without affecting other elements on the page.
- Adjusted the CSS styling for the heart icon to ensure proper alignment with the other icons (calendar and chat).
- No major structural changes were made, maintaining the overall design intact.
- Tested on different screen sizes to ensure responsiveness.
- Verified that the change does not affect other elements.
- This is a minor frontend change aimed at improving the user interface consistency.
=> change-like-align

index.html
I have fixed the issue that when a user click on image / text to a blog , it redirects the user to the blog page.
Uploading Untitled video - Made with Clipchamp000 (1).mp4…
=> chore: when user clicks on image, it directs him to the blog page

give_feedback.html, style.css
Hello, PR
Add new feature Star rating widget - #1045 #1076
Done -
=> Add Star rating widget done ! 

about.html, blog.html, category.html, contact_us.html, fashion.html, food.html, give_feedback.html, health.html, index.html, life.html, start_writing.html, style.css, tech.html, travel.html
Closes: #981 
Applied styling on social media Icons and changed social media icons with a hover effect , fixed all the missing icons.
*Improvements:*
1. *Optimized social media icons:* Enhanced the social media icons and its animation on the about, blog, category, fashion, contact_us, food,give_feedback, health, index, life, start_writing, tech, and travel pages to improve user experience.
2. *Revamped Social media icons Design:* Redesigned the Social media icons with modern CSS styling to enhance visual appeal.
3. *Update StyleSheet:* update CSS file to enhance styling and functionality, ensuring better code organization and maintainability.
The program was tested locally on a machine using the Chrome browser. To verify the changes, the website was loaded after the modifications were …
=> improve social media icons

index.html, style.css
Hello, PR
Fixed issue - #1073 #1094   #1096
Before - #1073 #1094
After - 
Home page -
Feedback page -
=> Fixed Navbar issue ! #1073 #1094

blog.html
Hello, PR
Fixed issue number - #1042 
Issue fixed -
=> Fixed FAQ section issue ! #1042

.github/workflows/PRValidator.yml
**What i have done :**
- Solved Adding github action workflow for PR validation
Fixes #1091
@ANSHIKA-26 
Pls add me labels like gssoc-extd,level3,hacktoberfest-accepted.
=> Added PR Validator Github Action

style.css
Closes #1077 
Eventhough the toggle functionality in password field was already added, the alignment of eye icon was not good...
I fixed the alignment user-friendly..
Before:(in both login and signup forms)
After:
@ANSHIKA-26 Kindly review the PR at the earliest
=> Changed alignment of toggle button in password field

blog.html, index.html
Reverts ANSHIKA-26/WordWise#1093
=> Revert "Added Search functionality"

blog.html
Hello PR,
Fixes #1043
Issue fixed(for both dark & light mode) & I also customize it by adding background color and shadow for both dark and light mode like other text boxes -
Before -
After -
=> Fixed text box issue ! #1043

Scroll_and_progressbar.css, about.html, blog.html, category.html, contact_us.html, give_feedback.html, index.html, start_writing.html, style.css
=> Created navbar sticky and set correct redirection links of navbar

about.html, blog.html, category.html, contact.html, contact_us.html, give_feedback.html, index.html, start_writing.html
Hello, PR
Fixed issue - #1044
Add new feature - Translation Tool
https://github.com/user-attachments/assets/7779ca09-50fe-48bb-b464-21415ac446cf
https://github.com/user-attachments/assets/f0bb2005-1899-4540-b139-a21ac8a7542b
=> Add Translation Tool done ! #1044

category.css, category.html
I have changed the color of footer titles and now they are visible. 
Before changes 
After changes 
https://github.com/user-attachments/assets/3c37364c-b253-4ff2-94ee-020255d78ca9
=> #1185  Feature/footer title

category.html, contact_us.html, index.html
=> Add Twitter Link to "Leading Blog" and "Start Writing" Sections (for all the pages)

style.css
Hello, PR
Fixed issue number - #1158 
Issue fixed -
=> Fixed Password section issue ! #1158

style.css
Issue Resolved: #1170
- [ x] I have added screenshots and videos to show before and after the working of my code.
- [ x] I have ensured that the screen size is set to 100% while making the video.
- [x ] I have synced the latest fork with my local repository and resolved any conflicts.
- [ x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x ] I understand that if any the above conditions are not met , my PR will not be MERGED .
=> alignment corrected

blog.html, bookmarks.html, style.css
Descriptions- 
Title- Bookmarking and Reading List feature #1179
Content- Bookmark Option added with MY Reading List page to display Bookmarked Articles
Feature: Implement a bookmarking feature that lets users save articles to a reading list.
How to Implement: Store bookmarks in the user’s browser …
=> Added Feature for Bookmarking and Reading List feature #1179

blog.html
https://github.com/user-attachments/assets/44ed19d3-a403-4c84-904d-e48b41d77e3a
=> Fixed text color and added shadows in categories section.

contact_us.js, frontend/src/styles/output.css, give_feedback.html
This PR introduces validation for the feedback and contact forms to ensure users provide valid data before submitting. Specifically, it includes checks for the email address format and displays appropriate error messages for invalid input. This enhancement improves the user experience by preventing the submission of incorrect data.
**Changes Made:**
1. *Email Validation:* Implemented a regular expression to validate email addresses before form submission.
2. *Error Messaging:* Added error messages that appear near the input fields when invalid data is detected.
3. *Form Submission Prevention:* The form will not be submitted unless all validation checks pass.
**Fixed Issue:**
Fixes #1228 
**Screenshoots:**
=> Add Validation to Feedback and Contact Forms to Prevent Invalid Data Submission

Carousel.js, index.html, style.css
=> Fixing carousel indicators in about section. 

blog.html, index.html
The footer section was improved for home and leading blog sections.
https://github.com/user-attachments/assets/be0ee6fc-67c1-47b0-a390-0741bf15f587
If appropriate please can you assign me level 2 label.
Thanking You
=> fixes#1249:[BUG]:Hovering of the footer section is not smooth

blog.html
https://github.com/user-attachments/assets/d321556e-2888-4515-8da6-673bcd452b9f
#1262
=> Comment Bug Fixed: Success Achieved!

category.css, category.html
=> Remove Faq button to Category Page

give_feedback.html
- #1316 
Fixes issue: #1316 
Before:
After:
=> [FIXED] Rate us not aligned propely #1316

index.html
Hello, PR
Issue fixed - #1314
https://github.com/user-attachments/assets/55f7ecd7-c0a8-4e99-9448-1efedf9c9eff
=> Fixed Feedback page button issue ! #1314

start_writing.css
1.Fixed invalid placeholder content for the textarea.
2.Added focus styles for form elements for better accessibility.
3.Smoothed transitions for the background and button hover effects.
4.Improved popup centering and ARIA role for accessibility.
5.Enhanced dark mode readability with better color contrast.
6.Added animations for the suggestions container (fade-in).
7.Optimized footer layout with gap for better spacing and responsiveness.
- [*] I have added screenshots and videos to show before and after the working of my code.
- [*] I have ensured that the screen size is set to 100% while making the video.
- [*] I have synced the latest fork with my local repository and resolved any conflicts.
- [*] I have mentioned the issue number which I created before making this PR .(format to …
=> Fixed Issues In start_writing.css

blog.html, style.css
Fixed issue - #1300 
The hover error on the text has been fixed When hovering it grows with some transition.
https://github.com/user-attachments/assets/b4f4fa55-e66f-4c97-a62a-0ff63bbe4ce0
=> Fixed Styling error on text in Leading blog 

style.css
=> Text-Alignment is not proper

index.html, style.css
This PR fixes #1357 
Before
https://github.com/user-attachments/assets/9517aec6-c458-4ba8-9378-9569353221f0
After
https://github.com/user-attachments/assets/fa5c8a17-3c75-4c54-85f2-1a8a6b3f98e7
=> fix: mobile ui issues

blog.html, darkMode.js, index.html, style.css
=> Enhanced Navbar design by giving clean look

index.html, style.css
it has been occurred for a previous issue [ issue #1337 ] which has been closed.
- Before
- After
=> Paragraph alignment

index.html
@ANSHIKA-26 
fixes #1351 
**Before working of code**
**After Working of Code**
=> Aligned the like button for cards

index.html, main.js, signup.css
Fixes: #1304 
https://github.com/user-attachments/assets/d212c25f-430e-4c92-ad37-ac41fd9ff9fe
- [x ] I have added screenshots and videos to show before and after the working of my code.
- [ x] I have ensured that the screen size is set to 100% while making the video.
- [ x] I have synced the latest fork with my local repository and resolved any conflicts.
- [ x] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [x ] I understand that if any the above conditions are not met , my PR will not be MERGED .
=> Password and confirm password vulnerability resolved.

index.html, main.js, signup.css
Fixes: #1305 
https://github.com/user-attachments/assets/01c337b8-eaa3-49a4-9afa-b7d687bcd481
- [X ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
=> navigation done between signup and login pages

style.css
Issue Fixed #1361 
The Social media icons hover size has been fix with normal increase when hover.
https://github.com/user-attachments/assets/ca3b5a36-2835-47b7-94b6-a167feafdf1e
=> Fixed Social Media Icons Increase Size on Hover

contact_us.html, start_writing.css, start_writing.html
Pull Request
Hi @ANSHIKA-26 ,
Issue Number - #1374 
I have fixed the styling for the "Start Writing Page" and "Contact Us" Page, I will be writing here what changes I have made in the code.
1. In Start_writing.html:
I have added a class called "add-collaborator" and "get_suggestions" for both buttons and by targeting these classes in start_writing.css I have given padding of 7px to enhance the look because they were a bit clumsy. (See screenshots)
2. In Starting_writing.css:
I have given the same box-shadow for the entire blog form container which was given on the "Home" page. I have commented on the earlier box-shadow. (See screenshots)
New box-shadow - box-shadow: 0px 3px 6px #fca5a5; 
Also the adjusted mic button on the container and added inline styling in start_writing.html.
=> Style …
=> Fixed the styling for Start Writing Page and Contact Us Page

blog.html
- [done ] I have added screenshots to show before and after the working of my code.
- [ done] I have synced the latest fork with my local repository and resolved any conflicts.
- [ done] I have mentioned the issue number which I created before making this PR .
fixes #1299 
- [ done] I understand that if any the above conditions are not met , my PR will not be MERGED .
=> Updated toggle switch to extreme right

backend/.env.example, backend/app.js, backend/controllers/blogController.js, backend/models/comment.js, backend/package-lock.json, backend/package.json, backend/routes/blogRoutes.js, blog-comment.js, blog.html
issue number #1392 
i added an api in the backend and and connect to the frontend now user comments are saved in the database
databse:
frontend:
please add gssoc-ext and level3 before merge @ANSHIKA-26
=> save comment to database

index.html
Fixes:#1428
The hovering of the login button was fixed.
After:
https://github.com/user-attachments/assets/d26fa6d9-3c49-43be-9a61-e20dc3536992
Before:
https://github.com/user-attachments/assets/b8a8df4b-cceb-4a25-ad59-5f6d793d0f76
Please give me level 1 for this issue.
=> The hovering of login button was improved.

bookmarks.html, style.css
Fix Issue - #1409 
I have resolved the issue where the dark theme styles were not applying to the bookmark.html page. Now, the background color updates correctly when dark mode is activated, ensuring a consistent user experience.
=> Correct Dark theme changes on Bookmark page

bookmarks.html
=> Add Language option in bookmark.html

blog.html, category.html, contact_us.html, give_feedback.html, index.html, script.js, start_writing.html, style.css
Fixes #1418 
all pages on laptop:
https://github.com/user-attachments/assets/54eea4d5-c5de-4f95-b4f4-c89177ff5022
responsive:
https://github.com/user-attachments/assets/a5b09133-ce4e-4e6e-8d2e-7db71e24a7fe
=> created navbar responsive across all screen sizes

index.html
This pull request updates the "Subscribe to Our Newsletter" section, which was previously static. I have implemented dynamic hover effects to enhance the user experience matching the theme of the website.
- **Heading Effect**: Added a grow effect on the "Subscribe to Our Newsletter" heading when hovered over, providing a more engaging visual cue.
- **Input Field Glow**: Implemented a dark pink glow effect around the input field border on hover, improving visibility and aesthetics.
- **Responsive Interaction**: Both the heading and the input field now respond to user interactions with smooth transitions.
These changes aim to create a more interactive and visually appealing experience for users, encouraging them to engage with the newsletter subscription.
fixes: #1298 
This issue was …
=> Implemented Dynamic Hover Effects to newsletter section

main.js
Fix #1467
- **Issue:** Fixes a bug where closing the signup popup displays the previously opened login popup.
- **Changes Made:** Updated logic to ensure only one popup is displayed at a time.
- **Improvements:** Enhanced event handling to close the current popup before opening a new one.
- **Testing:** Verified that the functionality works correctly for both login and signup popups.
- **Review:** Please check the changes for any further improvements.
@ANSHIKA-26 
Pls review the code and assign me, Also give me labels like level2,gssoc-extd,hacktoberfest-accepted.
=> Updated overlapping of login and signup popup forms

blog.html
@ANSHIKA-26  
Fixes #1397 
**Before working of code**
**Dark Mode**
**Light Mode**
**After Working of Code**
**Dark Mode**
**Light Mode**
=> Modified next and prev post section on blog page

category.css
fixes #1404
Before 
After 
Video 
https://github.com/user-attachments/assets/10ac379a-e972-493d-add5-4243e92b75b8
=> footer width corrected

blog.html, category.html, contact_us.html, give_feedback.html, index.html, start_writing.html
**PR: Add Page Titles to All HTML Files**
Fixes : #1503
- Added appropriate `<title>` tags to the `<head>` section of all HTML files, ensuring each title is relevant and unique.  
- Tested to confirm all pages display correct titles in browser tabs, improving SEO, accessibility, and user experience.  
@ANSHIKA-26 
Pls add labels like hacktoberfest-accepted, gssoc-extd, and level.
=> Adding Page Titles for All HTML Files

contact_us.html
- [done ] I have added screenshots and videos to show before and after the working of my code.
- [ done] I have ensured that the screen size is set to 100% while making the video.
- [done ] I have synced the latest fork with my local repository and resolved any conflicts.
- [ done] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [done ] I understand that if any the above conditions are not met , my PR will not be MERGED .
=> Conflits and sync fork done  , issue #1217

backend/controllers/userController.js, backend/package-lock.json, backend/package.json, backend/routes/userRoutes.js, main.js, resetpass.html
i added forgot password functinality   issue #1499
when the user click reset password an email will be sent to the user email with a link
email:
it will redirect user to a new page where he can reset the password
please add gssoc-ext and level3 before merge @ANSHIKA-26
=> added reset password functionality

frontend/src/index.html
issue #1525 
Added AI based chatbot to website
trained on our website data
it will answer the querry of user by his own intelligency and our website data
=> Added AI based chatbot 

index.html, script.js, words.json
@ANSHIKA-26 
Fixes: #1523 
**Screenshots**
**Before**
**After**
=> Changed the word of the day section

frontend/src/pages/BloggerProfile.js, frontend/src/pages/Login.js, frontend/src/styles/output.css, frontend/src/utils/router.js
issue title : Personal profile page for blogger
issue : #1535
https://github.com/user-attachments/assets/b82ba586-2a9d-45a4-8748-db763ec2a151
added personal profile page where blogger can save the draft of blog 
also see his profile details 
integrated with login details 
for better user experience 
Write modular and maintable code so that backend integration become easy
beautiful designed suits website theme !!
IF CHANGES REQUIRED THEN COMMENT BELOW I'LL DO IT
- [X ] I have mentioned the issue number which I created before …
=> Added profile page for blogger theme oriented

blog.html
=> aligned moon icon on toggle button in blog.html

category.css, style.css
=> Correct Category Page Footer Text Background

style.css
=> fixed home page card UI

frontend/src/pages/AddBlog.js, frontend/src/pages/Blogs.js, frontend/src/pages/ReadMoreBlog.js, frontend/src/styles/output.css, frontend/src/utils/router.js
issue #1574 
https://github.com/user-attachments/assets/6fbc92fa-b03e-4206-9b27-f5c013dc7171
I HAVE ADDED READ MORE PAGE AS WE CLICK ON BLOG READ MORE SECTION IT MOVE TO READMORE PAGE WHERE FULL DETAIILS OF BLOG CAN BE SHOWNED
if any ui enhancement need comment below i will do it 
Add good level tag !
- [ X] I have added screenshots and videos to show before and after the working of my code.X
- [X ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
- [X ] I understand that if any the above conditions are not met , my PR will not be …
=> added read more page

index.html
=> Added Navigate to top button which is fully functional

.vscode/settings.json, index.html, style.css
- .(format to mention issue number is : fixes #(1549) )
=> Change shadow effect on card

index.html, style.css
=> fixed css of heart and comment icon on home page

backend/app.js, backend/controllers/getInTouchController.js, backend/models/getInTouch.js, backend/routes/getInTouchRoutes.js, frontend/src/pages/About.js
issue #1602 
from get submitted successfully !1
=> Added backend for get in touch form

backend/app.js, backend/controllers/addBlogController.js, backend/models/addBlog.js, backend/package-lock.json, backend/routes/addBlogRoutes.js, frontend/src/pages/AddBlog.js, frontend/src/pages/Blogs.js
issue #1612 
https://github.com/user-attachments/assets/02a3fc85-0b78-4431-ab95-133cd975b9a3
i have handle blog submission carefully with proper folder structrue
along with creating the API for add blog page
i use this data to show on our main blog page if someone click on publish blog
- [X ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
=> Added backend for add blog page also render the blog data on blogPage

blog.html, category.html, contact.html, index.html, privacy.html, script.js, start_writing.html, style.css
Fix #986
A website counter has been implemented to dynamically track and display the total number of visitors. This feature enhances user engagement by showcasing the site’s popularity in real-time.
@ANSHIKA-26 
Pls give me labels, level, and assign me.
=> Implemented website visitor count dynamically

category.css
Issue fixed #1598 
This pull request aims to enhance the visual appeal and user experience of the category cards. The goal is to make the cards more engaging and easier to interact with.
**Updated Card Design:**
- redesign the cards content section 
- improving the content layout
https://github.com/user-attachments/assets/f5b6aed6-f5fa-4818-96ee-5f1abdaa2574
=>  Improve Card Design in Category Section

backend/controllers/addBlogController.js, category.css, frontend/src/pages/BloggerProfile.js, frontend/src/pages/Blogs.js, frontend/src/styles/output.css, start_writing.html
Before:
https://github.com/user-attachments/assets/ee151ed3-8187-4159-b22f-99101980c686
After:
https://github.com/user-attachments/assets/d621f84b-1cce-4b7a-992d-53bd41af3767
=> link the popular tags

index.html, profile.html, style.css, testp.css, testp.js
Hello, PR
Add new feature - #1599
Add a normal user profile page and a profile icon in the home page navbar that redirects to the profile page done -
Home page -
Profile page -
https://github.com/user-attachments/assets/682b7809-f34a-49a9-a099-99a29e1871c0
=> Add a User Profiles page done ! #1599

privacy.html
PR : Added Sticky Header to Privacy Policy Page for Enhanced Accessibility
Fix #1616 
**PR Description:**
- Implemented a sticky header for the privacy policy page to keep it visible during scrolling.
- Enhances user experience by maintaining easy access to privacy information.
- Ensures the policy remains prominent as users navigate through the content.
@ANSHIKA-26 
Pls assign me this, give me labels, level.
=> Added Sticky Header to Privacy Policy Page for Enhanced Accessibility

frontend/src/components/Footer.js, frontend/src/components/Navbar.js, frontend/src/index.html, frontend/src/pages/About.js, frontend/src/pages/AddBlog.js, frontend/src/pages/BloggerProfile.js, frontend/src/pages/Blogs.js, frontend/src/pages/Categories.js, frontend/src/pages/Contact.js, frontend/src/pages/Feedback.js, frontend/src/pages/Home.js, frontend/src/pages/ReadMoreBlog.js, frontend/src/styles/output.css
issue : #1629 
https://github.com/user-attachments/assets/79c51412-8cd6-4ba6-bd78-22b8774ba0d5
Added animation on full website for better scrolling experience to user
Enhance smoothness of website
make it look more beautiful on rendering
consistent animation
Note :  if any enhancement needed comment below i will do it !!
- [ X] I understand that if any the above conditions are not met , my …
=> Added animation on scroll on full website

frontend/src/components/Footer.js, frontend/src/pages/GoogleTranslator.js, frontend/src/styles/output.css
issue : #1656 
https://github.com/user-attachments/assets/f231e864-6fc0-4919-9261-d182c480a0b3
in video its not showing options block but when you click on select language it will show you many option as shown in SS
=> Added google translator for full website

frontend/package.json, frontend/src/main.js, frontend/src/pages/About.js, frontend/src/pages/AddBlog.js, frontend/src/pages/Contact.js, frontend/src/pages/Feedback.js, frontend/src/styles/output.css
issue : #1670 
https://github.com/user-attachments/assets/ea4361ec-1500-451d-a3ea-d407d0000ca5
Added toastr in all the pages where it is necessary 
=> Added toaster on all pages

frontend/src/pages/Blogs.js, frontend/src/styles/output.css
issue : #1677 
https://github.com/user-attachments/assets/4ce93384-5405-4721-9e64-8678f62dbb71
added play and pause button where it will read the following title and content of blog 
smoothly in clear clean voice 
Write modular and maintainable code 
will i get level 3 for it  , IT May look easy but its doesn't ?
- [ X] I understand that if any the above conditions are not met , my PR will …
=> Added text to speak functionality

frontend/src/components/Footer.js, frontend/src/pages/TermsOfUse.js, frontend/src/styles/output.css, frontend/src/utils/router.js
issue : #1680 
Description
This PR introduces a new "Terms of Use" page to the application, outlining the terms and conditions that govern the use of our services. The document includes various sections that define user obligations, intellectual property rights, limitation of liability, dispute resolution, and more, providing a comprehensive legal framework for users.
Changes Made
Created a new page named TermsOfUse.
Structured the content into relevant sections for clarity:
Acceptance of Terms
User Obligations
Intellectual Property Rights
Limitation of Liability
Indemnification
Termination Clause
Governing Law
Modification of Terms
Legal Compliance
Dispute Resolution
https://github.com/user-attachments/assets/1b789c4b-f6f5-40e5-ae63-24584070207f
- [ X] I have added screenshots and videos …
=> Added a clean and clear terms of use page

frontend/src/pages/Blogs.js, frontend/src/styles/output.css, frontend/src/utils/router.js
issue : #1678 
https://github.com/user-attachments/assets/b599160b-461d-4c39-9585-b0fae81c2d41
Added social media icon on blog post 
as you click on share icon it will reender you to the social media
and replace the title with real title of our blog dynamically 
and also provide the link of our blog post 
User can share the blog post efficiently 
enhance user experience 
can i get level 2 for it
- [ X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue …
=> Added social media sharing icon

blog.html, contact_us.css, style.css
=> fixed alignment of icons in footer

frontend/src/pages/Login.js, index.html
Adding "remember me" to the signup and signin page connecting it to the local storage database for user authentication. 
issue no. : #1675 
https://github.com/user-attachments/assets/bc7eade0-3b9d-47dc-83da-c9170a7e9cfd
=> Added "remember me" to the signup and signin page connecting it to the local storage database for user authentication. 

frontend/src/pages/BloggerProfile.js, frontend/src/pages/Login.js, frontend/src/styles/output.css
issue : #1707
https://github.com/user-attachments/assets/8f6b665d-c2bd-428b-825e-9adbb0777308
Maked profile page responsive and also fixes some issue in login page 
as its creating some problem in rendering 
=> Maked profile page responsive and also fixes some issues in login page

backend/app.js, backend/controllers/subscribeController.js, backend/models/subscribe.js, backend/routes/subscribeRoutes.js, backend/utils/sendMailToSubscribe.js, frontend/src/components/Footer.js, frontend/src/styles/output.css
issue : #1710 
https://github.com/user-attachments/assets/5092cb70-9ff6-4693-b4d6-bd5640bb3ce1
This PR introduces the "Subscribe Us" feature to the backend, enabling users to subscribe to the platform by submitting their name and email
Once subscribed, users receive a welcome email with details about the platform and its offerings.
Also saved the details of the user in the database for future !!
- [ X] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue …
=>  Added subscribe us feature on newsletter 

profile.html
=> made profile section responsive

backend/.env.example, backend/controllers/feedController.js, backend/sendFeedbackToAdmin.js, frontend/src/pages/Feedback.js, frontend/src/pages/Login.js, frontend/src/styles/output.css
issue : #1709 
https://github.com/user-attachments/assets/bb77bc1d-3382-4977-9bdd-96904258a2a8
create .env in backend folder
as mention in .env.example fill the field
passkey you will get form the mail , manage account , application password (12 character)
=> send the user feedback data to admin on mail

frontend/src/components/Navbar.js, frontend/src/pages/Login.js, frontend/src/styles/navbar.css, frontend/src/styles/output.css
issue : #1708 
https://github.com/user-attachments/assets/e8d27d10-ddcc-42ef-acc9-be3d0ab89ca4
=> Maked hamburger working on smaller screen

contact_us.html, give_feedback.html, index.html, start_writing.css, start_writing.html, style.css
Fixes issue no #1671
I added scroll button contact us , feedback, categories page , I will add the scroll button in start writing page later there is a error occurring but you can merge the PR in regard to other pages
=> fixed scroll btn

index.html, profile.html
Fixes issue number #1725 
The Edit profile option is started working now so that user can edit it's profile with the javascript, 
here's the output of it, 
https://github.com/user-attachments/assets/90007f0e-3f1b-4cce-9d8b-c9dfd4e227a3
Dear @ANSHIKA-26 , please merge this pull request.
=> Editing Of profile is working now with the help of JavaScript

index.html, profile.html, profileedit.html, testp.js
Hello, PR
Add Edit Profile Feature in Profile Page done -
https://github.com/user-attachments/assets/6697eafa-ab96-464b-b64e-17741ffac834
=> Add Edit Profile Feature in Profile Page done🟢

blog.html, category.html, contact_us.html, give_feedback.html, index.html, start_writing.html
=> added profile section on rest of the pages

contact_us.html
fixes #1751
- Adds validation to the mobile number field in the "Get in Touch" form.
- Restricts the mobile number field to numeric input only.
- Sets a maximum length of 10 digits to ensure valid phone number formatting.
- Improves data consistency and enhances user experience by preventing invalid data entry in the mobile number field.
=> Added Contact Form Mobile Number Validation

comment1.html, comment10.html, comment11.html, comment12.html, comment13.html, comment14.html, comment2.html, comment3.html, comment4.html, comment5.html, comment6.html, comment7.html, comment8.html, comment9.html, contact.html, fashion.html, food.html, health.html, life.html, style.css, tech.html, travel.html
Fixes: #1737
Before:
After:
Dark mode:
Light mode:
-
@ANSHIKA-26  Please review my change I have made change in all the category section
=> Update mismatch footer in category section

category.html, fashion.html
https://github.com/user-attachments/assets/26eb4466-cf83-4b15-8960-fb6c7c7ef732
=> Category section ->  image changes

contact_us.js
=> contact_us updated

blog.html, bookmarks.html, category.html, chatbot.html, fashion.html, frontend/src/index.html
- [YES] I have added screenshots and videos to show before and after the working of my code.
- [YES] I have ensured that the screen size is set to 100% while making the video.
- [YES] I have synced the latest fork with my local repository and resolved any conflicts.
- [YES] I have mentioned the issue number which I created before making this PR . fixes #1779 
- [YES] I understand that if any the above conditions are not met , my PR will not be MERGED .
=> SMOOTH SCROLLERBAR

blog.html
- [YES] I have added screenshots and videos to show before and after the working of my code.
- [YES] I have ensured that the screen size is set to 100% while making the video.
- [YES] I have synced the latest fork with my local repository and resolved any conflicts.
- [YES] I have mentioned the issue number which I created before making this PR . fixes #1773 
- [YES] I understand that if any the above conditions are not met , my PR will not be MERGED .
=> GIVES SUITABLE COLORS

backend/controllers/contactController.js, backend/routes/contactRoute.js, index.html
issue number #1753
added api to send email to the user who subscribe the newsletter  and also designed the email template
frontend request to api :
email demo:
please add level3 before merge @ANSHIKA-26
=> added newsleeter api and template

backend/app.js, backend/controllers/faqController.js, backend/models/answers.js, backend/models/question.js, backend/routes/faqRoutes.js
I have added the necessary backend models (tables) in the database, route handlers and API endpoints for the functionality of  faq forum a screen recording of working endpoints tested using postman have been attached, subsequent PR will include the frontend implementation of the same feature.
PR1: #1734
=> Added backend for forum

backend/app.js, backend/controllers/faqController.js, backend/models/answers.js, backend/models/question.js, backend/routes/faqRoutes.js, forum.html, index.html
added frontend for FAQ forum 
https://github.com/user-attachments/assets/9bbafb7e-c6ac-4b77-9295-f9f7f266efc6
PR2 and closes #1734
=> added frontend for FAQ page 

index.html, style.css
=> Update index.html and style.css

blog.html, category.html, contact_us.css, contact_us.html, give_feedback.html, index.html, start_writing.html, style.css
<br><br>
in all files footer updated, both version desktop and mobile.
=> Issue number #1780 and #1781 is solved

blog.html, bookmarks.html, category.html, comment1.html, comment10.html, comment11.html, comment12.html, comment13.html, comment14.html, comment2.html, comment3.html, comment4.html, comment5.html, comment6.html, comment7.html, comment8.html, comment9.html, contact.html, contact_us.html, fashion.html, food.html, gaming_chronicles.html, give_feedback.html, health.html, life.html, privacy.html, start.html, start_writing.html, tech.html, travel.html
=> Changed the scrollup button

backend/generateFromAi.py, backend/models/addBlog.js, frontend/src/pages/AddBlog.js, frontend/src/styles/output.css
issue : #1802 
Fixes : #1802 
https://github.com/user-attachments/assets/c8f3b389-8725-40b3-82fc-7b69f147b0b6
Introduced a dynamic approach for generating and displaying categories and tags powered by AI.
Now, the categories and tags are automatically populated, ensuring seamless updates and more accurate content representation.
Key Features:
Dynamic Category Population: Categories are automatically fetched and presented in a dropdown, including a default "Select Category" option for better UX.
Intelligent Tagging System: Tags are fetched dynamically to keep the content up-to-date and relevant.
Enhanced User Experience: Users can now select categories and tags with ease, improving content discoverability and user engagement.
- [ X] I have added screenshots and videos to show before and …
=> "✨ Dynamic Category and Tags Integration Using AI ✨"

style.css
=> fixes #1809 [color of word of the day and sentences]

index.html
=> linked blog.html

contact_us.html
=> Fixes issue #1814 [Add icons on contact us page.]

index.html
Issue Number #1622
- **"Improved scroll button functionality for smoother user experience."**
- **"Updated scroll button style and fixed alignment issues for better usability."**
- **"Enhanced scroll button responsiveness and design to improve navigation flow."** 
**Screenshot**
Please review and merge it @ANSHIKA-26 .
=> updating scroll button in main page
