ANSHIKA-26/WordWise

style.css
Fix text color blending with background in blog post section
This PR resolves the issue where the pink text for the date and comment icons was blending into the light pink background, making it hard to read. The following changes were made:
- Changed the text color to a darker shade for better contrast.
- Added a subtle text shadow to improve visibility if necessary.
Fixes  #4
Tested across multiple browsers (e.g., Chrome, Firefox) to ensure readability and consistency.
Let me know if further adjustments are needed
=> Fix text color blending issue in blog post section

.gitignore, package.json
Fixed #37 
I have initialized the npm package with git ignore files
=> Fixes #37 initialized npm package to setup the backend

index.html, style.css
###Description
This PR addresses fixing issue #530 by aligning the load more button in center and applying some animation on button.
[Screencast from 2024-10-08 14-20-21.webm](https://github.com/user-attachments/assets/900d4951-4fc4-462d-965f-a39350d61b6b)
=> fix center alignment of button issue #530 

about.html, blog.html, contact_us.html, index.html, start.html, start_writing.html
I have added an eye button next to the password field to toggle between showing and hiding the password. This improves the user experience by allowing users to verify their password as they type.
Fixes #541 
---
- Added an eye icon next to the password field.
- Implemented JavaScript logic to toggle password visibility.
- Styled the eye icon using CSS.
=> passward show icon added

contact_us.html
Hovering of send button in Contact Us and Feedback forms was fixed.
Before:
https://github.com/user-attachments/assets/28ac6f7f-f7bd-4752-9517-9f311b0bdbd2
After:
https://github.com/user-attachments/assets/05b7ceac-be49-4b68-a333-bbcd48375da4
Please give me level 1 on this issue
=> Fixes#783:The Send Button in both of the forms (Contact us and Feedback) is not hovering

category.css
The hover effect in the categories section is not aligned with the color theme of the website. When hovering over the category menu items, the colors do not match the expected pastel color scheme used throughout the website.
1. Open the website’s index.html file.
2. Launch the website using Live Server.
3. Navigate to the Menu Categories section.
4. Hover over any category item.
Before:
[before.webm](https://github.com/user-attachments/assets/78217a04-e09d-451f-b14d-773ee0cfc2ec)
After:
[after.webm](https://github.com/user-attachments/assets/60776c1a-852f-459a-b27a-f85306d5dca7)
=> Category Section Hover Effect Color Theme Issue

blog.html
Fixes: #625 
1. Stylish Design:
- Uses a gradient background with animated color transitions
- Implements a modern, card-based layout for comments
- Utilizes custom fonts and a carefully crafted color scheme
2. Comment Submission:
- Provides a form for users to submit new comments
- Includes fields for the commenter's name and comment text
- Features floating labels for input fields
- Offers a visually appealing submit button with hover effects
3. Nested Comments:
- Supports replies to existing comments
- Displays replies indented under their parent comments
4. Dynamic Comment Rendering:
- Renders comments and replies dynamically using JavaScript
- Updates the comment list in real-time when new comments are added
5. Like Functionality:
- Allows users to like comments
- Displays the number …
=> Create Comment and discussion Section

backend/package-lock.json, backend/package.json, backend/server.js
**Description:**  
- Resolved `ReferenceError: cookieParser is not defined` in the backend.  
- Imported and initialized the `cookie-parser` middleware correctly.
**Steps to Test:**  
1. Run `npm install cookie-parser` if not installed.  
2. Verify backend functionality and ensure cookies are parsed without errors.
**Issue Reference:**  
Fixes the `ReferenceError: cookieParser is not defined`.  
**Reviewers:**  
@ANSHIKA-26
Fixes #989
=> Solved Error `ReferenceError: cookieParser is not defined` in Backend

style.css
Fixes #1079
Issue: Stretched images on index.html
I've fixed the issue of stretched images on index.html through this PR.
Before:
After:
Looking forward to merge this PR.
Kindly add the tags of hacktoberfest, hacktoberfest-accepted and gssoc-ext.
=> Adjusted the images on index.html

blog.html
Updates the "Name" field in the **Join the conversation** section to only accept alphabetical letters (a-z, A-Z), preventing invalid or spam submissions.
- Added input validation to the "Name" field.
Before- 
After -
=> 🛠️FIX : Join the conversation - Name field validation

index.html, style.css
https://github.com/user-attachments/assets/05689ae8-98ac-4086-b76a-023ef05262d9
Issue #1283
=> Enhanced Hover Effects for Article Listings #1283

style.css
- #1334 
Fixes #1334 
The scrolling feature on the Start Writing page wasn't available and as a result the users weren't able to access the contents present down below and not able to write or post new blogs. This issue was fixed by removing the overflow condition that prevented the scrolling of the page.
https://github.com/user-attachments/assets/e0be1f24-4251-464d-ae37-eeb692ec7495
=> [FIXED] Page not scrolling on Start Writing page #1334

style.css
Inconsistent size of login and signup buttons on hover
before changes
https://github.com/user-attachments/assets/e06c9dc8-fc13-4283-a881-e8afc4e79719
https://github.com/user-attachments/assets/9eeaac1c-a86d-43f2-aede-3ff80b5e2d07
after changes
https://github.com/user-attachments/assets/f0638b4f-e63d-4971-95cc-97669277aa15
=> #1383 Fixed Inconsistent size of login and signup buttons on hover 

contact_us.js
Fixes #1470
1. Added validation to allow only trusted email domains: `gmail.com`, `outlook.com`, `yahoo.com`, `protonmail.com`, `icloud.com`, `tutanota.com`, and more.  
2. Displays an alert message if the email is from an untrusted domain and blocks submission.  
3. Ensures data integrity by filtering spam and temporary emails. 
@ANSHIKA-26 
Pls add level, gssoc-extd, hacktoberfest-accepted.
=> Added trusted email validation functionality in contact us page

give_feedback.html
Fixes #1485
1. Added validation to allow only trusted email domains: `gmail.com`, `outlook.com`, `yahoo.com`, `protonmail.com`, `icloud.com`, `tutanota.com`, and more.  
2. Displays an alert message if the email is from an untrusted domain and blocks submission.  
3. Ensures data integrity by filtering spam and temporary emails. 
@ANSHIKA-26 
Pls add level, gssoc-extd, hacktoberfest-accepted.
=> Added Trusted email validation functionality in feedback form

blog.html, category.html, start_writing.html, style.css
=> Made footer consistent in responsive layouts

start_writing.css
- Added a pink border on hover and focus for input fields and text areas to enhance user experience.
- Included a subtle pink shadow effect on focus for better visual feedback.
- Used !important to ensure styles are applied consistently across all input elements without interference from other styles.
- Verified that the pink border appears on hover and focus for each form field.
- Confirmed that shadow effect is visible on focus for a more engaging and accessible form design.
Let me know if any adjustments are needed.
fixes: #1466
=> Improve Form Styling with Focus Effects

backend/app.js, backend/controllers/feedbackcontroller.js, backend/models/feedback.js, backend/routes/feebackroute.js, give_feedback.html
i added backend and frontend function to save user feed back to the database   issue number #1498
demo:
save feedback:
data saved in database:
please add gssoc-ext and level3 before merge @ANSHIKA-26
=> added api modal route and function for saving user feedback

index.html, style.css
=> Redesigned Word of The Day

frontend/src/pages/Blogs.js, frontend/src/styles/output.css
issue title :  Add search bar on blog page
ISSUE #1529 
https://github.com/user-attachments/assets/9d535504-af93-4c26-971d-bbe5a5a104f1
Added search functionality !! 
- [X ] I have mentioned the issue number which I created before making this PR .(format to mention issue number is : fixes #(issue number) ) 
=> Added search functionality on blog page

contact_us.html
Fixes Issue: #1555
On the Contact page, when users type in the "Message" field, the input text does not appear. This lack of visibility prevents users from reviewing their message, which could lead to incomplete or incorrect submissions.
1. Go to the Contact page.
2. Click on the "Message" field and start typing.
3. Notice that the input text is not visible.
When typing in the "Message" field, the input text should appear, allowing users to see what they are typing.
This PR addresses the issue by ensuring that the textarea for the "Message" field has the correct styling. The color and background-color properties are updated to provide sufficient contrast. Additionally, any potential CSS overrides are managed with !important flags to prevent other styles from impacting the text visibility.
=> Fix invisible text in the "Message" field on the Contact page

backend/app.js, backend/controllers/contactController.js, backend/models/contact.js, backend/routes/contactRoute.js, frontend/src/pages/Contact.js
=> Added backend api for contanct us with proper folder structure

index.html, style.css
Description: Enhanced website performance by preloading critical external stylesheets with deferred loading for non-essential styles. Consolidated duplicate Font Awesome versions and reduced redundant requests by combining local CSS files. Improved page load speed and resource efficiency without compromising functionality.
Fixes #1605 
https://github.com/user-attachments/assets/b702ee6f-1ffc-4c94-a107-24ba59e935ad
=> Optimized website load time

blog.html, contact.html, gaming_chronicles.html, index.html, privacy.html
Fix #1637 
This PR addresses a CORS policy issue that blocks access to the Font Awesome Kit script by replacing it with a direct link to the Font Awesome CDN stylesheet. The change avoids cross-origin JavaScript requests, which caused errors in local development. Using the CDN link provides the same icon functionality without additional configuration, ensuring all icons load reliably across environments.
@ANSHIKA-26 
Pls assign me this, give me level, label.
=> Solved CORS Policy Blocking Access to FontAwesome Script issue.

style.css
Fixes: #1648 
Before:
After:
Light mode:
Dark mode:
=> fix the text visibility(Issue: #1648)

frontend/src/pages/Blogs.js, frontend/src/styles/output.css
issue : #1662
Added theme oriented no blog found page 
For both light and dark theme !
Better user experience 
=> Added no blog found page

bookmarks.html
Fixes #1690 
After:
https://github.com/user-attachments/assets/1aa68d31-f9a0-4540-a349-c792a93e482b
=> Added js for profile icon, login, signup and hamburger menu in responsive mode

backend/app.js, backend/controllers/discussionController.js, backend/models/discussion.js, backend/routes/discussionRoutes.js, frontend/src/pages/DiscussionForum.js, frontend/src/styles/output.css
issue : #1786 
fixes: #1786 
https://github.com/user-attachments/assets/40f19071-b924-4e59-9ef9-26e5e80dba1e
This PR introduces the backend functionality for a Question and Answer (Q&A) forum on the website. The following features have been implemented:
Schema Definition: The schema for Question and Answer has been added to the database.
Backend Actions:
createQuestion: A backend action that allows authenticated users to create questions.
createAnswer: A backend action that allows authenticated users to answer questions.
getAnsweredQuestions: A backend action to fetch all answered questions, available to all users.
getUnansweredQuestions: A backend action to fetch all unanswered questions, available to all users.
API Endpoints:
The endpoints for testing all route have been created 
- [ X] …
=> Added backend api for both answered and unanswered question

profile.html, testp.css
fixes #1760
This PR addresses the UI inconsistency with the "Save" and "Cancel" buttons in the Profile section. The buttons were not aligned correctly and had inconsistent styling compared to the rest of the interface. This fix adjusts the CSS to ensure that both buttons are visually aligned and styled consistently with the design guidelines.
- **Changes made**:
- Fixed misalignment of the "Save" and "Cancel" buttons.
- Updated CSS to match the design guidelines for button styling in the Profile section.
- Ensured consistent spacing and layout of the buttons.
=> Fixed Save and Cancel Button UI

profile.html, testp.css
fixes #1758
This PR implements a functional "Change Password" modal that opens when the "Change Password" button is clicked. It includes input fields for the current password, new password, and password confirmation. The modal also ensures that the entered passwords match and meet any necessary password requirements.
- Implemented the "Change Password" modal that opens on button click.
- Added input fields for the current password, new password, and password confirmation.
- Integrated validation to ensure the new passwords match and meet the required criteria.
- Added error handling to display validation or submission errors.
=> Added Password Change Modal

index.html, start_writing.css, style.css
This pull request addresses the issues with the social media icons, including the suboptimal hover effect and alignment problems. The following improvements have been made:
- Refined Hover Effect: The hover effect on the social media icons has been refined to provide a more subtle and similar animation as leading page.
- Improved Alignment: The icons have been properly aligned to ensure a clean and consistent layout.
- Enhanced Visual Consistency: The icons have been styled to match the overall design language of the website.
https://github.com/user-attachments/assets/80e006bf-f0cf-4d8d-ab94-3b8c9ca3313c
=> fixed social media icons and unalign icons

profile.html, profile.js
Closes: #1790 
https://github.com/user-attachments/assets/a81be1bb-70f2-4629-8b7d-7c7f178c7bd9
=> Proper Profile Page (Dynamic)

index.html
Solved :
Issue No #1810 
After the user stops typing in the email field, the debounce function waits for 500 milliseconds. If the user hasn’t typed anything new, the validateEmail function runs to check the email format And shows error.
=> Added Debouncing Effect to SignUp page

frontend/src/pages/Stories.js, frontend/src/styles/output.css, frontend/src/utils/router.js
https://github.com/user-attachments/assets/a3e876a0-f629-4927-a3f1-f8f87c0a90c4
This feature implementation creates a Stories page where bloggers can easily view and submit posts.
It allows bloggers to publish content with a title, category, and description, enabling them to manage their stories effectively. 
The page provides an intuitive interface for interacting ,
allowing users to seamlessly create, store, and view their posts.
.
- [X ] I have mentioned the issue number which I created before making this PR .(format to …
=> ✨ Builded a Stories Page: Enable Bloggers to Create and View stories / experience of other blogger !!✨🔥

backend/app.js, backend/controllers/postsController.js, backend/models/postModel.js, backend/routes/storiesRoutes.js, frontend/src/components/Footer.js, frontend/src/pages/Stories.js, frontend/src/styles/output.css
issue : #1830
fixes : #1830 
This PR implements the backend for the Stories page, including the following:
GET /api/posts: Fetches all the stories (posts) from the database.
POST /api/posts: Allows users to create and save new stories by submitting title, content, and category data.
The data is stored in a MongoDB database using Mongoose, and the backend handles both the creation and retrieval of posts.
Changes include:
Creation of routes and controllers for handling posts.
Integration of Mongoose for database interaction.
Validation to ensure necessary fields are provided before saving a new post.
This sets up the backend to support the stories functionality on the frontend.
- [ X] I have ensured …
=> Build Backend for Stories Page: Implement  CURD operation Routes ✨🚀

start_writing.css, start_writing.js
Fixes #1834
Made the necessary changes to startwriting.html, and the corresponding CSS and JS file to make the back to top button visible again.
=> Back to Top Button Disappears on Start Writing Tab During Scroll
